version: '3'
services:
  myapp-main:
    image: s4_sdat_qap2_db:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/s4_sdat_qap2_db
      #- spring.datasource.url=jdbc:mysql://s4_sdat_qap2_db.ce2vcezehro2.us-east-1.rds.amazonaws.com/s4_sdat_qap2_db
      - spring.datasource.password=Optical81101
      - spring.datasource.username=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
